[package]
name = "proptest-http-message"
version = "0.1.0"
edition = "2024"

[dependencies]
array-concat = "0.5.5"
proptest = "1.8.0"
rand = "0.9.2"

[dev-dependencies]
claims = "0.8.0"
url = "2.5.7"
