name: Cargo Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  verifications:
    uses: ./.github/workflows/rust-verifications.yml

  # Optional job to verify the latest dependencies work
  latest_deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true # This prevents a failure from blocking the entire pipeline[citation:2]
    env:
      CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: allow # Allows testing with newer deps[citation:2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo update --verbose # Update to the latest compatible versions
      - run: cargo build --verbose
      - run: cargo test --verbose
