name: Publish to crates.io

on:
  push:
    tags: ["v*"]

jobs:
  verifications:
    uses: ./.github/workflows/rust-verifications.yml

  publish:
    name: Publish
    needs: verifications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
